#:schema node_modules/wrangler/config-schema.json
name = "zylsmk"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "cc8fd1ea4d9242b99db782df81a9ebc3" }
]

[assets]
directory = "./public"
